// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import FilterLunchesController from "./filter_lunches_controller"
application.register("filter-lunches", FilterLunchesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SwapSubscriptionController from "./swap_subscription_controller"
application.register("swap-subscription", SwapSubscriptionController)
