// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActiveCurrentGroupController from "./active_current_group_controller"
application.register("active-current-group", ActiveCurrentGroupController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import CopyLinkController from "./copy_link_controller"
application.register("copy-link", CopyLinkController)

import FilterLunchesController from "./filter_lunches_controller"
application.register("filter-lunches", FilterLunchesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationSubscriptionController from "./notification_subscription_controller"
application.register("notification-subscription", NotificationSubscriptionController)

import SwapSubscriptionController from "./swap_subscription_controller"
application.register("swap-subscription", SwapSubscriptionController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
